# Generated by Django 3.1.3 on 2020-12-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('sort_field', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('url_to_video', models.URLField(verbose_name='Ссылка на видеофайл')),
                ('url_to_subtitle', models.URLField(blank=True, default='', verbose_name='Ссылка на файл субтитров')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to='api_app.page')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('sort_field', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('text', models.TextField(help_text='Поле для хранения текста произвольной длинны', verbose_name='Текстовое поле')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_texts', to='api_app.page')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текст',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Счетчик просмотров')),
                ('sort_field', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('bitrate', models.FloatField(help_text='Битрейт в количестве бит в секунду', verbose_name='Битрейт')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_audios', to='api_app.page')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
            },
        ),
    ]
